global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'kafka-jmx-kafka1'
    static_configs:
      - targets: ['kafka1:9991']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'kafka-jmx-kafka2'  
    static_configs:
      - targets: ['kafka2:9992']
    scrape_interval: 15s
    metrics_path: /metrics

  - job_name: 'kafka-jmx-kafka3'
    static_configs:
      - targets: ['kafka3:9993']
    scrape_interval: 15s
    metrics_path: /metrics