server:
  port: 8080

spring:
  application:
    name: transaction-producer
  
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: kafka
    password: kafka-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Application properties
ecommerce:
  kafka:
    topics:
      transactions: transactions

logging:
  level:
    com.ecommerce: DEBUG
    org.springframework.kafka: INFO