server:
  port: 8085

spring:
  application:
    name: fraud-consumer
    
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: kafka
    password: kafka-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        
  # Kafka Configuration
  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: fraud-detection-group
      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

# Actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging configuration
logging:
  level:
    com.ecommerce.fraud: INFO
    org.apache.kafka: WARN
    org.springframework.kafka: INFO
  file:
    name: ../logs/fraud-consumer.log